/*
 * This source file was generated by the Gradle 'init' task
 */
package net.ddns.advaith.blocks.plugin.sqlite3;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
